/*
 * WINDREAM recompilation - import bridge helpers (after pod-recomp).
 *
 * A bridge runs inside the recomp stack model. RECOMP_ICALL has pushed a dummy
 * return address, so from ESP the stack is [ret][arg0][arg1]... Every Win32
 * import WINDREAM uses is stdcall: the bridge pops its own arguments.
 *
 *   ARG(n)     argument n (0-based), a 32-bit slot
 *   PTR(va)    guest VA -> host pointer (arena)
 *   RET(v)     set EAX
 *   STDRET(k)  pop the dummy return address and k argument slots
 */
#ifndef WD_IMPORTS_H
#define WD_IMPORTS_H

#include "recomp_types.h"

#define ARG(n)      MEM32(g_esp + 4 + (n) * 4)
#define PTR(va)     ((void*)(uintptr_t)ADDR(va))
#define RET(v)      do { g_eax = (uint32_t)(v); } while (0)
#define STDRET(k)   do { g_esp += 4 + (uint32_t)(k) * 4; } while (0)

#define IMPORT_STUB(nm) do { \
    static int _w = 0; \
    if (!_w) { fprintf(stderr, "[import-stub] %s\n", (nm)); _w = 1; } \
} while (0)

/* Guest memory layout (guest VAs; host = arena + VA). */
#define WD_TIB_BASE     0x00010000u   /* main thread TIB (one page)            */
#define WD_STACK_BASE   0x00100000u   /* main thread stack, 2 MB               */
#define WD_STACK_SIZE   0x00200000u
#define WD_IMAGE_BASE   0x00400000u   /* WINDREAM.EXE                          */
#define WD_HEAP_BASE    0x01000000u   /* VirtualAlloc / shim allocations       */
#define WD_HEAP_SIZE    0x30000000u   /* 768 MB                                */
#define WD_ARENA_SIZE   (WD_HEAP_BASE + WD_HEAP_SIZE)

/* runtime.c */
uint32_t shim_alloc(uint32_t n, uint32_t align);      /* zeroed, never freed */
uint32_t shim_strdup(const char* s);
void     guest_strcpy_out(uint32_t va, uint32_t cap, const char* s);
int      guest_str(uint32_t va, char* out, int cap);  /* copy a guest C string */
uint32_t wd_image_span(void);

/* files.c */
void     files_init(const char* exe);

/* vm.c: VirtualAlloc/VirtualFree/VirtualQuery over the guest heap region */
uint32_t vm_alloc(uint32_t addr, uint32_t size, uint32_t type, uint32_t prot);
int      vm_free(uint32_t addr, uint32_t size, uint32_t type);
uint32_t vm_query(uint32_t addr, uint32_t mbi_va);
const char* vm_describe(uint32_t va);

/* threads.c */
void     wd_thread_init_main(void);

/* handles.c: guest handle <-> host HANDLE for files and find handles */
uint32_t handle_new(void* host, int kind);
void*    handle_get(uint32_t gh, int kind);
void     handle_close(uint32_t gh);
enum { HK_FILE = 1, HK_FIND = 2, HK_STD = 3, HK_MAP = 6 };

/* runtime.c: calling back into lifted code, and synthetic COM methods */
extern const char* g_wd_exe;                           /* host path of the guest EXE */
uint32_t guest_call(uint32_t va, int argc, const uint32_t* args);  /* stdcall into lifted code */
#define WD_COM_BASE 0xCD000000u                        /* synthetic COM method VAs */
uint32_t wd_com_vtable(const recomp_func_t* fns, int n);
recomp_func_t wd_com_lookup(uint32_t va);

/* USER and GDI handles are 32-bit significant on 64-bit Windows (documented
 * for WOW64 interop), so the guest holds the real handle, truncated. */
#define H32(h)      ((uint32_t)(uintptr_t)(h))
#define HHOST(v)    ((void*)(intptr_t)(int32_t)(v))

/* user.c */
void     host_init(void);
uint32_t host_elapsed_ms(void);
extern int g_wd_quiet;                                 /* WD_QUIET: log message boxes, don't show */

/* dsound.c */
void     mixer_cd_play(const char* path, int track);   /* NULL path stops */
void     mixer_cd_pause(int paused);
int      mixer_cd_playing(void);

/* imports_gen.c (generated by gen_imports.py) */
extern const recomp_dispatch_entry_t wd_import_bridges[];
extern const uint32_t wd_import_bridge_count;

#endif /* WD_IMPORTS_H */
