/*
 * KERNEL32 bridge host for kernel_bridge_smoke.py.
 *
 * A DLL holding the production host bridges (files, kernel, threads, vm) and
 * the production runtime setup (arena, image loader, IAT). The Python side
 * maps the arena into Unicorn, runs retail x86 from GDIDREAM.EXE there and
 * hands every import the guest reaches to kb_call, so the code under test is
 * the bridge C and its only caller is original code.
 *
 * kernel_bridge_imports.inc is generated by the script: the KERNEL32 imports
 * with a hand-written bridge, and the entry point.
 */
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include "imports.h"

#define KB_EXPORT __declspec(dllexport)
/* Guest thread procedures the script assembles live at KB_CODE + n * KB_STEP,
 * in the committed bottom of the main stack region. */
#define KB_CODE 0x00110000u
#define KB_STEP 0x100u

struct kb_import { uint32_t address; recomp_func_t func; const char* name; };
#include "kernel_bridge_imports.inc"

/* ---- what runtime.c links against but this host never runs ---- */
void host_init(void) { abort(); }
void recomp_install_crash_handler(void) { }
void recomp_set_region_describer(const char* (*fn)(uint32_t)) { (void)fn; }
int recomp_trace_arg(int argc, char** argv, int i) { (void)argc; (void)argv; (void)i; return 0; }
void recomp_trace_flush(void) { }
void recomp_trace_help(void) { }
void wd_scene_probe_init(void) { abort(); }
void wd_render_install(void) { abort(); }
void wd_render_close(void) { abort(); }
uint32_t wd_surface_invalidate_range(uint32_t base, uint32_t bytes) { (void)base; (void)bytes; return 0; }
int wd_unused_main(int argc, char** argv);

/* ---- guest threads: the bridge looks the procedure up, the script runs it ---- */
typedef void (*kb_thread_fn)(uint32_t* regs);   /* {eax, esp, fs base, va} */
static kb_thread_fn g_thread_cb;
static void thread_enter(uint32_t va) {
    uint32_t regs[4] = { g_eax, g_esp, g_fs_base, va };
    if (!g_thread_cb) abort();
    g_thread_cb(regs);
    g_eax = regs[0]; g_esp = regs[1];
}
#define KB_TRAMP(n) static void tramp##n(void) { thread_enter(KB_CODE + n * KB_STEP); }
KB_TRAMP(0) KB_TRAMP(1) KB_TRAMP(2) KB_TRAMP(3) KB_TRAMP(4) KB_TRAMP(5) KB_TRAMP(6) KB_TRAMP(7)
static void entry_unused(void) { abort(); }
const recomp_dispatch_entry_t recomp_dispatch_table[] = {
    { KB_CODE + 0 * KB_STEP, tramp0 }, { KB_CODE + 1 * KB_STEP, tramp1 },
    { KB_CODE + 2 * KB_STEP, tramp2 }, { KB_CODE + 3 * KB_STEP, tramp3 },
    { KB_CODE + 4 * KB_STEP, tramp4 }, { KB_CODE + 5 * KB_STEP, tramp5 },
    { KB_CODE + 6 * KB_STEP, tramp6 }, { KB_CODE + 7 * KB_STEP, tramp7 },
    { KB_ENTRY, entry_unused },
};
const uint32_t recomp_dispatch_count = 9;

#define KB_IMPORTS (sizeof kb_imports / sizeof kb_imports[0])
/* runtime.c would fill the IAT from this table; the script points every slot
 * at its own gate page instead. */
const recomp_dispatch_entry_t wd_import_bridges[] = { { 0, NULL } };
const uint32_t wd_import_bridge_count = 0;

static recomp_func_t find(const char* name) {
    for (size_t i = 0; i < KB_IMPORTS; i++)
        if (!strcmp(kb_imports[i].name, name)) return kb_imports[i].func;
    return NULL;
}

/* The guest's last-error value, kept across the Python between two calls
 * (ctypes and the interpreter call Win32 themselves). It is read and written
 * only through the bridges, so the host works for any implementation of them. */
static __declspec(thread) uint32_t t_error;
static uint32_t scratch(void) { return g_fs_base + 0x800u; }   /* unused half of the TIB page */
static void error_put(void) {
    uint32_t esp = g_esp, eax = g_eax;
    g_esp = scratch();
    WD_HOST_WRITE32(g_esp + 4) = t_error;
    find("SetLastError")();
    g_esp = esp; g_eax = eax;
}
static void error_get(void) {
    uint32_t esp = g_esp, eax = g_eax;
    g_esp = scratch();
    find("GetLastError")();
    t_error = g_eax;
    g_esp = esp; g_eax = eax;
}

/* regs: {eax, esp, last error}. esp points at the return address, as it does
 * when the guest's `call [slot]` lands; the bridge pops it and its arguments. */
KB_EXPORT void kb_call(uint32_t index, uint32_t* regs) {
    if (index >= KB_IMPORTS) abort();
    g_eax = regs[0]; g_esp = regs[1];
    g_cur_func = kb_imports[index].address;
    error_put();
    kb_imports[index].func();
    error_get();
    regs[0] = g_eax; regs[1] = g_esp; regs[2] = t_error;
}

KB_EXPORT uint32_t kb_error(void) { return t_error; }
KB_EXPORT void kb_set_error(uint32_t value) { t_error = value; }

KB_EXPORT int kb_init(const char* exe, const char* guest_exe) {
    char* argv[] = { "kernel_bridge", (char*)exe, NULL };
    /* Without --run: arena, image, IAT and the main thread's stack and TIB. */
    if (wd_unused_main(2, argv)) return 0;
    files_init(guest_exe);
    return 1;
}
KB_EXPORT void* kb_arena(void) { return (void*)g_mem_base; }
KB_EXPORT uint32_t kb_fs_base(void) { return g_fs_base; }
KB_EXPORT uint32_t kb_esp(void) { return g_esp; }
KB_EXPORT void kb_set_thread_callback(kb_thread_fn fn) { g_thread_cb = fn; }
KB_EXPORT uint32_t kb_import_count(void) { return (uint32_t)KB_IMPORTS; }
KB_EXPORT uint32_t kb_import_address(uint32_t i) { return kb_imports[i].address; }
KB_EXPORT const char* kb_import_name(uint32_t i) { return kb_imports[i].name; }

/* Committed ranges of the arena, as {va, bytes} pairs: what Unicorn may map. */
KB_EXPORT uint32_t kb_committed(uint32_t* out, uint32_t capacity) {
    uint32_t n = 0;
    uint64_t va = 0;
    while (va < WD_ARENA_SIZE) {
        MEMORY_BASIC_INFORMATION info;
        if (!VirtualQuery(PTR((uint32_t)va), &info, sizeof info)) break;
        uint64_t end = (uint64_t)((uintptr_t)info.BaseAddress - (uintptr_t)g_mem_base) + info.RegionSize;
        if (end > WD_ARENA_SIZE) end = WD_ARENA_SIZE;
        if (info.State == MEM_COMMIT) {
            if (n < capacity) { out[n * 2] = (uint32_t)va; out[n * 2 + 1] = (uint32_t)(end - va); }
            n++;
        }
        va = end;
    }
    return n;
}
