[sdl]
fullscreen = false
output = surface
windowresolution = 1280x960

[dosbox]
machine = svga_s3
memsize = 32
captures = E:\dev\dreams\out\recomp\dosbox\capture-x
quit warning = false

[render]
aspect = true
scaler = none

[cpu]
core = dynamic
cputype = pentium_mmx
cycles = fixed 200000

[voodoo]
voodoo_card = software
voodoo_maxmem = false
glide = false

[autoexec]
mount d "E:\dev\dreams\out\recomp\dosbox\disc1" -t cdrom
mount c "E:\dev\dreams\out\recomp\dosbox\c"
c:
cd \CRYO\DREAMS
AUTOTYPE -w 12 -p 3 esc enter
DREAMSFX.EXE
exit
