[sdl]
fullscreen = false
window_size = 1280x960
pause_when_inactive = off

[render]
shader = sharp
integer_scaling = off
aspect = on
image_adjustments = off

[dosbox]
machine = svga_s3
memsize = 32

[cpu]
core = dynamic
cputype = pentium_mmx
cpu_cycles = 200000

[voodoo]
voodoo = true
voodoo_memsize = 4

[capture]
capture_dir = E:\dev\dreams\out\recomp\dosbox\capture
default_image_capture_formats = raw

[autoexec]
mount d "E:\dev\dreams\out\recomp\dosbox\disc1" -t cdrom
mount c "E:\dev\dreams\out\recomp\dosbox\c"
c:
cd \CRYO\DREAMS
DREAMSFX.EXE
exit
