/*
 * WINDREAM recompilation - compile-time check of guest_win32.h against the
 * Windows SDK (built on Windows only; it contributes no code).
 */
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <mmsystem.h>
#include <stddef.h>
#include "guest_win32.h"

#define SAME(a, b) _Static_assert((a) == (b), #a " != " #b)
#define AT(type, field, off) _Static_assert(offsetof(type, field) == (off), #type "." #field)

SAME(W32_WM_CREATE, WM_CREATE); SAME(W32_WM_DESTROY, WM_DESTROY);
SAME(W32_WM_CLOSE, WM_CLOSE); SAME(W32_WM_QUIT, WM_QUIT); SAME(W32_PM_REMOVE, PM_REMOVE);
SAME(W32_WS_VISIBLE, WS_VISIBLE); SAME(W32_CW_USEDEFAULT, (unsigned)CW_USEDEFAULT);
SAME(W32_SM_CXSCREEN, SM_CXSCREEN); SAME(W32_SM_CYSCREEN, SM_CYSCREEN);

SAME(W32_MB_TYPEMASK, MB_TYPEMASK); SAME(W32_MB_ICONMASK, MB_ICONMASK); SAME(W32_MB_DEFMASK, MB_DEFMASK);
SAME(W32_MB_OK, MB_OK); SAME(W32_MB_OKCANCEL, MB_OKCANCEL);
SAME(W32_MB_ABORTRETRYIGNORE, MB_ABORTRETRYIGNORE); SAME(W32_MB_YESNOCANCEL, MB_YESNOCANCEL);
SAME(W32_MB_YESNO, MB_YESNO); SAME(W32_MB_RETRYCANCEL, MB_RETRYCANCEL);
SAME(W32_MB_ICONHAND, MB_ICONHAND); SAME(W32_MB_ICONQUESTION, MB_ICONQUESTION);
SAME(W32_MB_ICONEXCLAMATION, MB_ICONEXCLAMATION); SAME(W32_MB_ICONASTERISK, MB_ICONASTERISK);
SAME(W32_IDOK, IDOK); SAME(W32_IDCANCEL, IDCANCEL); SAME(W32_IDABORT, IDABORT);
SAME(W32_IDRETRY, IDRETRY); SAME(W32_IDIGNORE, IDIGNORE); SAME(W32_IDYES, IDYES); SAME(W32_IDNO, IDNO);

SAME(W32_VK_LBUTTON, VK_LBUTTON); SAME(W32_VK_RBUTTON, VK_RBUTTON); SAME(W32_VK_MBUTTON, VK_MBUTTON);
SAME(W32_VK_XBUTTON1, VK_XBUTTON1); SAME(W32_VK_XBUTTON2, VK_XBUTTON2);
SAME(W32_VK_BACK, VK_BACK); SAME(W32_VK_TAB, VK_TAB); SAME(W32_VK_CLEAR, VK_CLEAR);
SAME(W32_VK_RETURN, VK_RETURN); SAME(W32_VK_SHIFT, VK_SHIFT); SAME(W32_VK_CONTROL, VK_CONTROL);
SAME(W32_VK_MENU, VK_MENU); SAME(W32_VK_PAUSE, VK_PAUSE); SAME(W32_VK_CAPITAL, VK_CAPITAL);
SAME(W32_VK_ESCAPE, VK_ESCAPE); SAME(W32_VK_SPACE, VK_SPACE); SAME(W32_VK_PRIOR, VK_PRIOR);
SAME(W32_VK_NEXT, VK_NEXT); SAME(W32_VK_END, VK_END); SAME(W32_VK_HOME, VK_HOME);
SAME(W32_VK_LEFT, VK_LEFT); SAME(W32_VK_UP, VK_UP); SAME(W32_VK_RIGHT, VK_RIGHT);
SAME(W32_VK_DOWN, VK_DOWN); SAME(W32_VK_SNAPSHOT, VK_SNAPSHOT); SAME(W32_VK_INSERT, VK_INSERT);
SAME(W32_VK_DELETE, VK_DELETE); SAME(W32_VK_LWIN, VK_LWIN); SAME(W32_VK_RWIN, VK_RWIN);
SAME(W32_VK_APPS, VK_APPS); SAME(W32_VK_NUMPAD0, VK_NUMPAD0); SAME(W32_VK_MULTIPLY, VK_MULTIPLY);
SAME(W32_VK_ADD, VK_ADD); SAME(W32_VK_SUBTRACT, VK_SUBTRACT); SAME(W32_VK_DECIMAL, VK_DECIMAL);
SAME(W32_VK_DIVIDE, VK_DIVIDE); SAME(W32_VK_F1, VK_F1); SAME(W32_VK_F10, VK_F10); SAME(W32_VK_F11, VK_F11);
SAME(W32_VK_NUMLOCK, VK_NUMLOCK); SAME(W32_VK_SCROLL, VK_SCROLL);
SAME(W32_VK_LSHIFT, VK_LSHIFT); SAME(W32_VK_RSHIFT, VK_RSHIFT); SAME(W32_VK_LCONTROL, VK_LCONTROL);
SAME(W32_VK_RCONTROL, VK_RCONTROL); SAME(W32_VK_LMENU, VK_LMENU); SAME(W32_VK_RMENU, VK_RMENU);
SAME(W32_VK_OEM_1, VK_OEM_1); SAME(W32_VK_OEM_PLUS, VK_OEM_PLUS); SAME(W32_VK_OEM_COMMA, VK_OEM_COMMA);
SAME(W32_VK_OEM_MINUS, VK_OEM_MINUS); SAME(W32_VK_OEM_PERIOD, VK_OEM_PERIOD); SAME(W32_VK_OEM_2, VK_OEM_2);
SAME(W32_VK_OEM_3, VK_OEM_3); SAME(W32_VK_OEM_4, VK_OEM_4); SAME(W32_VK_OEM_5, VK_OEM_5);
SAME(W32_VK_OEM_6, VK_OEM_6); SAME(W32_VK_OEM_7, VK_OEM_7); SAME(W32_VK_OEM_102, VK_OEM_102);

SAME(W32_BI_RGB, BI_RGB); SAME(W32_BI_BITFIELDS, BI_BITFIELDS); SAME(W32_OPAQUE, OPAQUE);
SAME(sizeof(BITMAPINFOHEADER), 40);
AT(BITMAPINFOHEADER, biSize, W32_BIH_SIZE); AT(BITMAPINFOHEADER, biWidth, W32_BIH_WIDTH);
AT(BITMAPINFOHEADER, biHeight, W32_BIH_HEIGHT); AT(BITMAPINFOHEADER, biBitCount, W32_BIH_BITCOUNT);
AT(BITMAPINFOHEADER, biCompression, W32_BIH_COMPRESSION); AT(BITMAPINFOHEADER, biClrUsed, W32_BIH_CLRUSED);
AT(RECT, right, W32_RECT_RIGHT); AT(RECT, bottom, W32_RECT_BOTTOM);

SAME(W32_MEM_COMMIT, MEM_COMMIT); SAME(W32_MEM_RESERVE, MEM_RESERVE);
SAME(W32_MEM_DECOMMIT, MEM_DECOMMIT); SAME(W32_MEM_RELEASE, MEM_RELEASE);
SAME(W32_MEM_FREE, MEM_FREE); SAME(W32_MEM_PRIVATE, MEM_PRIVATE); SAME(W32_MEM_IMAGE, MEM_IMAGE);
SAME(W32_PAGE_NOACCESS, PAGE_NOACCESS); SAME(W32_PAGE_READWRITE, PAGE_READWRITE);
/* The guest's 32-bit MEMORY_BASIC_INFORMATION: pointer fields are 4 bytes, so
 * only the field order is shared with the host's layout; sizes are checked
 * against the 32-bit value vm_query returns. */
SAME(W32_MBI_SIZE, 28);

SAME(W32_MAX_PATH, MAX_PATH);
SAME(W32_INVALID_FILE_ATTRIBUTES, INVALID_FILE_ATTRIBUTES);
SAME(W32_INVALID_SET_FILE_POINTER, INVALID_SET_FILE_POINTER);
SAME(W32_GENERIC_READ, GENERIC_READ); SAME(W32_GENERIC_WRITE, GENERIC_WRITE);
SAME(W32_CREATE_NEW, CREATE_NEW); SAME(W32_CREATE_ALWAYS, CREATE_ALWAYS);
SAME(W32_OPEN_EXISTING, OPEN_EXISTING); SAME(W32_OPEN_ALWAYS, OPEN_ALWAYS);
SAME(W32_TRUNCATE_EXISTING, TRUNCATE_EXISTING);
SAME(W32_FILE_ATTRIBUTE_DIRECTORY, FILE_ATTRIBUTE_DIRECTORY);
SAME(W32_FILE_ATTRIBUTE_ARCHIVE, FILE_ATTRIBUTE_ARCHIVE);
SAME(W32_FILE_TYPE_UNKNOWN, FILE_TYPE_UNKNOWN); SAME(W32_FILE_TYPE_DISK, FILE_TYPE_DISK);
SAME(W32_FILE_TYPE_CHAR, FILE_TYPE_CHAR);
SAME(W32_STD_INPUT_HANDLE, STD_INPUT_HANDLE); SAME(W32_STD_OUTPUT_HANDLE, STD_OUTPUT_HANDLE);
SAME(W32_CREATE_SUSPENDED, CREATE_SUSPENDED); SAME(W32_INFINITE, INFINITE);
SAME(W32_WAIT_OBJECT_0, WAIT_OBJECT_0); SAME(W32_WAIT_TIMEOUT, WAIT_TIMEOUT);
SAME(W32_WAIT_FAILED, WAIT_FAILED); SAME(W32_TLS_OUT_OF_INDEXES, TLS_OUT_OF_INDEXES);
SAME(W32_CP_ACP, CP_ACP); SAME(W32_CP_OEMCP, CP_OEMCP); SAME(W32_CP_THREAD_ACP, CP_THREAD_ACP);
SAME(W32_FIND_DATA_SIZE, sizeof(WIN32_FIND_DATAA));
AT(WIN32_FIND_DATAA, cFileName, W32_FIND_DATA_NAME);
AT(WIN32_FIND_DATAA, ftLastWriteTime, 20); AT(WIN32_FIND_DATAA, nFileSizeHigh, 28);
AT(WIN32_FIND_DATAA, nFileSizeLow, 32); AT(WIN32_FIND_DATAA, cAlternateFileName, 304);
SAME(W32_ERROR_FILE_NOT_FOUND, ERROR_FILE_NOT_FOUND); SAME(W32_ERROR_PATH_NOT_FOUND, ERROR_PATH_NOT_FOUND);
SAME(W32_ERROR_TOO_MANY_OPEN_FILES, ERROR_TOO_MANY_OPEN_FILES);
SAME(W32_ERROR_ACCESS_DENIED, ERROR_ACCESS_DENIED); SAME(W32_ERROR_INVALID_HANDLE, ERROR_INVALID_HANDLE);
SAME(W32_ERROR_NOT_ENOUGH_MEMORY, ERROR_NOT_ENOUGH_MEMORY); SAME(W32_ERROR_NO_MORE_FILES, ERROR_NO_MORE_FILES);
SAME(W32_ERROR_FILE_EXISTS, ERROR_FILE_EXISTS); SAME(W32_ERROR_INVALID_PARAMETER, ERROR_INVALID_PARAMETER);
SAME(W32_ERROR_INSUFFICIENT_BUFFER, ERROR_INSUFFICIENT_BUFFER);
SAME(W32_ERROR_NEGATIVE_SEEK, ERROR_NEGATIVE_SEEK); SAME(W32_ERROR_ALREADY_EXISTS, ERROR_ALREADY_EXISTS);
SAME(W32_ERROR_INVALID_ADDRESS, ERROR_INVALID_ADDRESS);
SAME(W32_ERROR_SHARING_VIOLATION, ERROR_SHARING_VIOLATION);
SAME(W32_ERROR_FILENAME_EXCED_RANGE, ERROR_FILENAME_EXCED_RANGE);

SAME(W32_JOYERR_NOERROR, JOYERR_NOERROR); SAME(W32_JOYERR_PARMS, JOYERR_PARMS);
SAME(W32_JOYERR_UNPLUGGED, JOYERR_UNPLUGGED);
SAME(W32_JOY_RETURNX, JOY_RETURNX); SAME(W32_JOY_RETURNY, JOY_RETURNY); SAME(W32_JOY_RETURNZ, JOY_RETURNZ);
SAME(W32_JOY_RETURNR, JOY_RETURNR); SAME(W32_JOY_RETURNU, JOY_RETURNU); SAME(W32_JOY_RETURNV, JOY_RETURNV);
SAME(W32_JOY_RETURNPOV, JOY_RETURNPOV); SAME(W32_JOY_RETURNBUTTONS, JOY_RETURNBUTTONS);
SAME(W32_JOY_POVCENTERED, JOY_POVCENTERED);
SAME(W32_JOYCAPS_HASZ, JOYCAPS_HASZ); SAME(W32_JOYCAPS_HASR, JOYCAPS_HASR); SAME(W32_JOYCAPS_HASU, JOYCAPS_HASU);
SAME(W32_JOYCAPS_HASPOV, JOYCAPS_HASPOV); SAME(W32_JOYCAPS_POV4DIR, JOYCAPS_POV4DIR);
SAME(W32_JOYCAPSA_SIZE, sizeof(JOYCAPSA));
AT(JOYCAPSA, wMid, W32_JC_MID); AT(JOYCAPSA, wPid, W32_JC_PID); AT(JOYCAPSA, szPname, W32_JC_PNAME);
AT(JOYCAPSA, wXmin, W32_JC_XMIN); AT(JOYCAPSA, wNumButtons, W32_JC_NUMBUTTONS);
AT(JOYCAPSA, wPeriodMin, W32_JC_PERIODMIN); AT(JOYCAPSA, wPeriodMax, W32_JC_PERIODMAX);
AT(JOYCAPSA, wRmin, W32_JC_RMIN); AT(JOYCAPSA, wCaps, W32_JC_CAPS); AT(JOYCAPSA, wMaxAxes, W32_JC_MAXAXES);
AT(JOYCAPSA, wNumAxes, W32_JC_NUMAXES); AT(JOYCAPSA, wMaxButtons, W32_JC_MAXBUTTONS);
SAME(W32_JOYINFOEX_SIZE, sizeof(JOYINFOEX));
AT(JOYINFOEX, dwFlags, W32_JI_FLAGS); AT(JOYINFOEX, dwXpos, W32_JI_XPOS);
AT(JOYINFOEX, dwButtons, W32_JI_BUTTONS); AT(JOYINFOEX, dwButtonNumber, W32_JI_BUTTONNUMBER);
AT(JOYINFOEX, dwPOV, W32_JI_POV);

SAME(W32_MCI_OPEN, MCI_OPEN); SAME(W32_MCI_CLOSE, MCI_CLOSE); SAME(W32_MCI_PLAY, MCI_PLAY);
SAME(W32_MCI_SEEK, MCI_SEEK); SAME(W32_MCI_STOP, MCI_STOP); SAME(W32_MCI_PAUSE, MCI_PAUSE);
SAME(W32_MCI_SET, MCI_SET); SAME(W32_MCI_STATUS, MCI_STATUS); SAME(W32_MCI_RESUME, MCI_RESUME);
SAME(W32_MCI_FROM, MCI_FROM); SAME(W32_MCI_OPEN_TYPE, MCI_OPEN_TYPE);
SAME(W32_MCI_SET_DOOR_OPEN, MCI_SET_DOOR_OPEN); SAME(W32_MCI_STATUS_ITEM, MCI_STATUS_ITEM);
SAME(W32_MCI_STATUS_NUMBER_OF_TRACKS, MCI_STATUS_NUMBER_OF_TRACKS);
SAME(W32_MCI_STATUS_MODE, MCI_STATUS_MODE); SAME(W32_MCI_STATUS_MEDIA_PRESENT, MCI_STATUS_MEDIA_PRESENT);
SAME(W32_MCI_STATUS_READY, MCI_STATUS_READY); SAME(W32_MCI_STATUS_CURRENT_TRACK, MCI_STATUS_CURRENT_TRACK);
SAME(W32_MCI_MODE_STOP, MCI_MODE_STOP); SAME(W32_MCI_MODE_PLAY, MCI_MODE_PLAY);
SAME(W32_MCI_MODE_PAUSE, MCI_MODE_PAUSE);
SAME(W32_MCIERR_INVALID_DEVICE_ID, MCIERR_INVALID_DEVICE_ID);
SAME(W32_MCIERR_UNRECOGNIZED_KEYWORD, MCIERR_UNRECOGNIZED_KEYWORD);
SAME(W32_MCIERR_OUTOFRANGE, MCIERR_OUTOFRANGE);
SAME(W32_MCIERR_MISSING_PARAMETER, MCIERR_MISSING_PARAMETER);
