"""Generate gen/imports_gen.c: one bridge per WINDREAM import.

A bridge is hand-written when some runtime/*.c file defines `void imp_<Name>(void)`;
otherwise a stub is emitted that logs once, returns 0 (or 1 for the names in
NONZERO) and pops the right number of stdcall argument slots. Argument counts
come from the Windows SDK's 32-bit import libraries (pcrecomp stdcall_argc.py),
not from a hand-typed table.

Defaults: the exe is DREAMS_DISC1/GDIDREAM.EXE, the output
DREAMS_OUT/recomp/windream/gen/imports_gen.c.

usage: uv run --with capstone --with pefile python recomp/windream/gen_imports.py [exe] [out.c]
"""

import glob
import os
import re
import sys

from dreams import paths

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, str(paths.get("pcrecomp") / "tools" / "pe"))
from pe_analyze import analyze_pe, build_iat_map  # noqa: E402
from stdcall_argc import ArgcResolver  # noqa: E402

NONZERO = {
    "GetDC",
    "CreateCompatibleDC",
    "SelectObject",
    "GetStockObject",
    "LoadIconA",
    "LoadCursorA",
    "RegisterClassA",
    "ShowWindow",
    "UpdateWindow",
    "SetBkMode",
    "StretchBlt",
    "DeleteDC",
    "DeleteObject",
    "ReleaseDC",
    "AdjustWindowRectEx",
    "GetClientRect",
    "FlushFileBuffers",
}


def main():
    exe = sys.argv[1] if len(sys.argv) > 1 else str(paths.disc(1) / "GDIDREAM.EXE")
    out = (
        sys.argv[2]
        if len(sys.argv) > 2
        else str(paths.get("out") / "recomp" / "windream" / "gen" / "imports_gen.c")
    )
    iat = build_iat_map(analyze_pe(exe))
    manual = set()
    for path in glob.glob(os.path.join(HERE, "runtime", "*.c")):
        if os.path.basename(path) == "imports_gen.c":
            continue
        manual |= set(re.findall(r"^void imp_(\w+)\(void\)", open(path).read(), re.M))
    argc = ArgcResolver()
    lines = [
        "/* WINDREAM recompilation - import bridges - GENERATED by gen_imports.py */",
        "#define RECOMP_GENERATED_CODE",
        '#include "imports.h"',
        "",
    ]
    rows = sorted(iat.items())
    unknown = []
    stubs = 0
    for _va, (dll, name) in rows:
        n = argc.lookup(dll, name)
        if n is None:
            unknown.append(f"{dll}!{name}")
            n = 0
        if name in manual:
            lines.append(f"void imp_{name}(void);  /* {dll}, {n} args: hand-written */")
        else:
            stubs += 1
            ret = "1" if name in NONZERO else "0"
            lines.append(
                f'static void imp_{name}(void) {{ IMPORT_STUB("{dll}!{name}"); '
                f"RET({ret}); STDRET({n}); }}"
            )
    lines += ["", "const recomp_dispatch_entry_t wd_import_bridges[] = {"]
    lines += [f"    {{ 0x{va:08X}u, imp_{name} }},  /* {dll}!{name} */" for va, (dll, name) in rows]
    lines += ["};", f"const uint32_t wd_import_bridge_count = {len(rows)};", ""]
    open(out, "w").write("\n".join(lines))
    print(f"{len(rows)} imports: {len(rows) - stubs} hand-written, {stubs} stubs -> {out}")
    if unknown:
        print("argument count unknown (stubbed as 0):", ", ".join(unknown))


if __name__ == "__main__":
    main()
